version: 2
updates:
  # Docker image updates (Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"   # Dockerfile is in root
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"

  # Python dependencies (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"   # requirements.txt is in root
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(pip)"
      include: "scope"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"   # .github/workflows/
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"