name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mstfknn/phishing-fasttext
          tags: |
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=Phishing Detection Model (FastText)
            org.opencontainers.image.description=Lightweight FastText model to classify domains as phishing or clean.
          flavor: |
            latest=true
          readme-file: ./DOCKERHUB.md

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}